_wandb:
    value:
        cli_version: 0.23.1
        e:
            kpoebrk9r91prc8839oowmwdx1x155di:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Apple M3 Pro
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "11811160064"
                codePath: training_scripts/train_balance.py
                codePathLocal: train_balance.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "413784047616"
                email: aarshsmittal@gmail.com
                executable: /Users/aarshmittal/miniconda3/envs/booster-ssl/bin/python
                git:
                    commit: 6533cc9f0cc045baba24b859aa18b9b706e679a5
                    remote: https://github.com/Ezimakyu/SAI_SoccerRL.git
                host: mac.lan
                memory:
                    total: "38654705664"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/aarshmittal/SAI_SoccerRL/training_scripts/./train_balance.py
                python: CPython 3.11.14
                root: /Users/aarshmittal/SAI_SoccerRL/training_scripts
                startedAt: "2026-01-05T07:10:20.484100Z"
                writerId: kpoebrk9r91prc8839oowmwdx1x155di
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 256
policy_clip:
    value: 0.35
push_up_w:
    value: 0.2
recovery_tilt:
    value: 0.35
stable_tilt:
    value: 0.15
timesteps:
    value: 400000
